#!/usr/bin/env bash
# Generate niro/credentials.yaml from the helpdesk's seeded local users.
#
# seed.py creates three demo accounts (2 customers, 1 agent) with
# well-known local passwords. They are not real secrets — committing
# this generator is the "generator script" pattern documented in
# niro/credentials.yaml.example.
#
# Also embeds mTLS client cert entries for the same three users, reading
# PEM files from niro/certs/ (generated by niro/gen-certs.sh). Run
# gen-certs.sh first if niro/certs/ does not exist.
#
# Also creates demo payload-signing credentials:
#   - HMAC-SHA256 shared secret for /signed/hmac.
#   - RSA-SHA256 private key for /signed/rsa.
#
# Rerun any time you want a fresh credentials.yaml.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/credentials.yaml"
CERTS="$SCRIPT_DIR/certs"
HMAC_SIGNING_SECRET="${HELPDESK_HMAC_SIGNING_SECRET:-demo-hmac-secret}"
RSA_SIGNING_KEY="$CERTS/signing-rsa.key"
RSA_SIGNING_PUB="$CERTS/signing-rsa.pub"

if [ ! -d "$CERTS" ]; then
  echo "niro/certs/ not found — run niro/gen-certs.sh first" >&2
  exit 1
fi

if [ ! -f "$RSA_SIGNING_KEY" ]; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$RSA_SIGNING_KEY" >/dev/null 2>&1
fi
openssl rsa -in "$RSA_SIGNING_KEY" -pubout -out "$RSA_SIGNING_PUB" >/dev/null 2>&1

# Indent a PEM file by 6 spaces for embedding as YAML block scalar content
# under 4-space-indented keys (e.g. "    cert_pem: |").
_indent() { sed 's/^/      /' "$1"; }

cat > "$OUT" <<'HEADER'
# Generated by niro/gen-credentials.sh. Do not edit by hand; rerun the
# script to regenerate.
credentials:
  - description: |
      Standard customer A. Login: POST /auth/login with form-encoded
      `username` (email) and `password`; response is
      {access_token, token_type:bearer}; send the token on subsequent
      calls as `Authorization: Bearer <token>`.
    type: username_password
    identifier: alex@customer.test
    secret: customer-pass-1234

  - description: |
      Standard customer B. Login: same shape as customer A.
    type: username_password
    identifier: blair@customer.test
    secret: customer-pass-1234

  - description: |
      Helpdesk agent (elevated role). Login: same shape as the customers.
    type: username_password
    identifier: agent@helpdesk.test
    secret: agent-pass-1234

HEADER

cat >> "$OUT" <<EOF
  - description: |
      Demo HMAC signer for POST /signed/hmac on port 8000. HMAC-SHA256 over the raw request body, base64, send as X-Signature.
    type: signing
    algorithm: hmac-sha256
    secret: ${HMAC_SIGNING_SECRET}

  - description: |
      Demo RSA signer for POST /signed/rsa on port 8000. RSA-SHA256 over the raw request body, base64, send as Signature.
    type: signing
    algorithm: rsa-sha256
    key_pem: |
EOF
_indent "$RSA_SIGNING_KEY" >> "$OUT"
echo "" >> "$OUT"

# Append mTLS entries with inline PEM blocks.
_mtls_entry() {
  local name="$1" cn="$2" desc="$3"
  echo "  - description: |"
  echo "      ${desc}"
  echo "      Present this cert during the TLS handshake to port 8443 — no Bearer token needed."
  echo "    type: mtls"
  echo "    cert_pem: |"
  _indent "$CERTS/client-${name}.crt"
  echo "    key_pem: |"
  _indent "$CERTS/client-${name}.key"
  echo "    ca_pem: |"
  _indent "$CERTS/ca.crt"
  echo ""
}

{
  _mtls_entry "alex"  "alex@customer.test"  "mTLS client cert for alex@customer.test (customer A) on the mTLS endpoint (port 8443)."
  _mtls_entry "blair" "blair@customer.test" "mTLS client cert for blair@customer.test (customer B) on the mTLS endpoint (port 8443)."
  _mtls_entry "agent" "agent@helpdesk.test" "mTLS client cert for agent@helpdesk.test (helpdesk agent) on the mTLS endpoint (port 8443)."
} >> "$OUT"

echo "→ wrote $OUT"
