#!/usr/bin/env python3
"""Generate deterministic Niro fixtures from the local helpdesk DB.

The repo's documented seed.py creates the README users. This generator builds
the cross-customer data Niro needs around those users and emits
niro/fixtures.yaml. The generated YAML is local-only; this script is the
committed rebuild primitive.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from sqlalchemy import select

CONFIG_DIR = Path(os.environ.get("NIRO_CONFIG_DIR", Path(__file__).resolve().parent)).resolve()
ROOT = Path(os.environ.get("NIRO_PROJECT_ROOT", CONFIG_DIR.parent)).resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.db import Base, SessionLocal, engine  # noqa: E402
from app.jobs import run_scheduled_report  # noqa: E402
from app.models import (  # noqa: E402
    Comment,
    Priority,
    ReportFrequency,
    SavedSearch,
    ScheduledReport,
    Status,
    Ticket,
    User,
)
from app.search import serialize_filter  # noqa: E402
from seed import main as seed_users  # noqa: E402

OUT = CONFIG_DIR / "fixtures.yaml"
FIXTURE_TAG = "[niro-fixture]"


def _user(db, email: str) -> User:
    user = db.scalar(select(User).where(User.email == email))
    if user is None:
        raise RuntimeError(f"missing seeded user: {email}")
    return user


def _clear_prior_fixtures(db) -> None:
    for saved in db.scalars(
        select(SavedSearch).where(SavedSearch.name.like(f"{FIXTURE_TAG}%"))
    ).all():
        db.delete(saved)
    db.flush()

    for ticket in db.scalars(
        select(Ticket).where(Ticket.subject.like(f"{FIXTURE_TAG}%"))
    ).all():
        db.delete(ticket)
    db.commit()


def _ticket(
    db,
    *,
    customer: User,
    agent: User,
    subject: str,
    description: str,
    priority: Priority,
    status: Status,
) -> Ticket:
    ticket = Ticket(
        customer_id=customer.id,
        assignee_id=agent.id,
        subject=f"{FIXTURE_TAG} {subject}",
        description=description,
        priority=priority,
        status=status,
    )
    db.add(ticket)
    db.flush()
    db.add(
        Comment(
            ticket_id=ticket.id,
            author_id=customer.id,
            body=f"{FIXTURE_TAG} customer-owned comment for {customer.email}",
        )
    )
    db.add(
        Comment(
            ticket_id=ticket.id,
            author_id=agent.id,
            body=f"{FIXTURE_TAG} agent triage note for {customer.email}",
        )
    )
    return ticket


def _saved_search(
    db,
    *,
    owner: User,
    name: str,
    filter_data: dict[str, Any],
    pinned: bool = False,
) -> SavedSearch:
    saved = SavedSearch(
        owner_id=owner.id,
        name=f"{FIXTURE_TAG} {name}",
        filter_json=serialize_filter(filter_data),
        pinned=pinned,
    )
    db.add(saved)
    db.flush()
    return saved


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))


def _write_yaml_value(lines: list[str], value: Any, indent: int) -> None:
    prefix = " " * indent
    if isinstance(value, dict):
        if not value:
            lines.append(f"{prefix}{{}}")
            return
        for key, item in value.items():
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}{key}:")
                _write_yaml_value(lines, item, indent + 2)
            else:
                lines.append(f"{prefix}{key}: {_yaml_scalar(item)}")
    elif isinstance(value, list):
        if not value:
            lines.append(f"{prefix}[]")
            return
        for item in value:
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}-")
                _write_yaml_value(lines, item, indent + 2)
            else:
                lines.append(f"{prefix}- {_yaml_scalar(item)}")
    else:
        lines.append(f"{prefix}{_yaml_scalar(value)}")


def _emit(fixtures: list[dict[str, Any]]) -> None:
    lines = [
        "# Generated by niro/gen-fixtures.py. Do not edit by hand; rerun the",
        "# script to regenerate after resetting or reseeding the local target.",
        "fixtures:",
    ]
    for fixture in fixtures:
        lines.append(f"  - name: {fixture['name']}")
        lines.append(f"    description: {json.dumps(fixture['description'])}")
        lines.append("    value:")
        _write_yaml_value(lines, fixture["value"], 6)
        lines.append("")
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    Base.metadata.create_all(bind=engine)
    seed_users()

    db = SessionLocal()
    try:
        _clear_prior_fixtures(db)

        agent = _user(db, "agent@helpdesk.test")
        alex = _user(db, "alex@customer.test")
        blair = _user(db, "blair@customer.test")

        alex_ticket = _ticket(
            db,
            customer=alex,
            agent=agent,
            subject="customer A login reset",
            description="Customer A cannot complete the password reset flow.",
            priority=Priority.urgent,
            status=Status.open,
        )
        blair_ticket = _ticket(
            db,
            customer=blair,
            agent=agent,
            subject="customer B billing export",
            description="Customer B needs the invoice export regenerated.",
            priority=Priority.high,
            status=Status.in_progress,
        )

        alex_search = _saved_search(
            db,
            owner=alex,
            name="customer A urgent tickets",
            filter_data={"customer_id": alex.id, "priority": Priority.urgent.value},
            pinned=True,
        )
        blair_search = _saved_search(
            db,
            owner=blair,
            name="customer B active tickets",
            filter_data={
                "customer_id": blair.id,
                "status": Status.in_progress.value,
            },
            pinned=True,
        )
        agent_search = _saved_search(
            db,
            owner=agent,
            name="agent all high priority",
            filter_data={"priority": Priority.high.value},
            pinned=False,
        )

        alex_schedule = ScheduledReport(
            saved_search_id=alex_search.id,
            frequency=ReportFrequency.daily,
            email="alex-reports@customer.test",
            next_run_at=datetime.now(UTC).replace(tzinfo=None) - timedelta(minutes=5),
        )
        db.add(alex_schedule)
        db.commit()
        db.refresh(alex_schedule)
        alex_run = run_scheduled_report(alex_schedule.id, db)

        alex_comment_ids = [
            c.id
            for c in db.scalars(
                select(Comment)
                .where(Comment.ticket_id == alex_ticket.id)
                .order_by(Comment.id.asc())
            ).all()
        ]
        blair_comment_ids = [
            c.id
            for c in db.scalars(
                select(Comment)
                .where(Comment.ticket_id == blair_ticket.id)
                .order_by(Comment.id.asc())
            ).all()
        ]

        fixtures = [
            {
                "name": "seeded_actor_ids",
                "description": (
                    "README seeded users present in this boot. Use for role "
                    "and identity-aware authorization checks."
                ),
                "value": {
                    "agent": {"id": agent.id, "email": agent.email, "role": agent.role.value},
                    "customer_a": {"id": alex.id, "email": alex.email, "role": alex.role.value},
                    "customer_b": {"id": blair.id, "email": blair.email, "role": blair.role.value},
                },
            },
            {
                "name": "cross_customer_ticket_pair",
                "description": (
                    "Different customer-owned tickets. Customer A owns only "
                    "customer_a_ticket_id; customer B owns only "
                    "customer_b_ticket_id; the agent may access both."
                ),
                "value": {
                    "customer_a_ticket_id": alex_ticket.id,
                    "customer_a_comment_ids": alex_comment_ids,
                    "customer_b_ticket_id": blair_ticket.id,
                    "customer_b_comment_ids": blair_comment_ids,
                    "agent_assignee_id": agent.id,
                },
            },
            {
                "name": "saved_search_pair",
                "description": (
                    "Different customer-owned saved searches plus an agent "
                    "search. Customers should not access another customer's "
                    "search or schedule surfaces."
                ),
                "value": {
                    "customer_a_search_id": alex_search.id,
                    "customer_b_search_id": blair_search.id,
                    "agent_search_id": agent_search.id,
                },
            },
            {
                "name": "customer_a_scheduled_report",
                "description": (
                    "Customer A recurring report with an initial run. Use "
                    "schedule_id and run_id for schedule/run-history "
                    "authorization checks."
                ),
                "value": {
                    "schedule_id": alex_schedule.id,
                    "saved_search_id": alex_search.id,
                    "initial_run_id": alex_run.id,
                    "recipient": alex_schedule.email,
                    "frequency": alex_schedule.frequency.value,
                },
            },
        ]
        _emit(fixtures)
        print(f"-> wrote {OUT}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
