#!/usr/bin/env bash
# Generate niro/credentials.yaml from the helpdesk's seeded local users.
#
# seed.py creates three demo accounts (2 customers, 1 agent) with
# well-known local passwords. They are not real secrets — committing
# this generator is the "generator script" pattern documented in
# niro/credentials.yaml.example.
#
# Rerun any time you want a fresh credentials.yaml.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/credentials.yaml"

cat > "$OUT" <<'EOF'
# Generated by niro/gen-credentials.sh. Do not edit by hand; rerun the
# script to regenerate.
credentials:
  - description: |
      Standard customer A. Login: POST /auth/login with form-encoded
      `username` (email) and `password`; response is
      {access_token, token_type:bearer}; send the token on subsequent
      calls as `Authorization: Bearer <token>`.
    type: username_password
    identifier: alex@customer.test
    secret: customer-pass-1234

  - description: |
      Standard customer B. Login: same shape as customer A.
    type: username_password
    identifier: blair@customer.test
    secret: customer-pass-1234

  - description: |
      Helpdesk agent (elevated role). Login: same shape as the customers.
    type: username_password
    identifier: agent@helpdesk.test
    secret: agent-pass-1234
EOF

echo "→ wrote $OUT"
