#!/usr/bin/env python3
"""Generate deterministic Niro fixtures from the local helpdesk DB.

The repo's documented seed.py creates the README users (agent, alex, blair).
This generator builds the cross-customer data Niro needs around those users —
tickets and comments OWNED BY DIFFERENT CUSTOMERS — and emits
niro/fixtures.yaml so horizontal-authorization tests (IDOR / cross-tenant)
have distinct cross-owner objects to reach.

It targets the current working-tree surface (tickets + comments + mTLS); it
does NOT assume the saved-search / scheduled-report feature. The generated
YAML is local-only; this script is the committed rebuild primitive.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

from sqlalchemy import select

CONFIG_DIR = Path(os.environ.get("NIRO_CONFIG_DIR", Path(__file__).resolve().parent)).resolve()
ROOT = Path(os.environ.get("NIRO_PROJECT_ROOT", CONFIG_DIR.parent)).resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.db import Base, SessionLocal, engine  # noqa: E402
from app.models import (  # noqa: E402
    Comment,
    Priority,
    Status,
    Ticket,
    User,
)
from seed import main as seed_users  # noqa: E402

OUT = CONFIG_DIR / "fixtures.yaml"
FIXTURE_TAG = "[niro-fixture]"


def _user(db, email: str) -> User:
    user = db.scalar(select(User).where(User.email == email))
    if user is None:
        raise RuntimeError(f"missing seeded user: {email}")
    return user


def _clear_prior_fixtures(db) -> None:
    # Deleting tagged tickets cascades to their comments
    # (Ticket.comments uses cascade="all, delete-orphan").
    for ticket in db.scalars(
        select(Ticket).where(Ticket.subject.like(f"{FIXTURE_TAG}%"))
    ).all():
        db.delete(ticket)
    db.commit()


def _ticket(
    db,
    *,
    customer: User,
    agent: User,
    subject: str,
    description: str,
    priority: Priority,
    status: Status,
) -> Ticket:
    ticket = Ticket(
        customer_id=customer.id,
        assignee_id=agent.id,
        subject=f"{FIXTURE_TAG} {subject}",
        description=description,
        priority=priority,
        status=status,
    )
    db.add(ticket)
    db.flush()
    db.add(
        Comment(
            ticket_id=ticket.id,
            author_id=customer.id,
            body=f"{FIXTURE_TAG} customer-owned comment for {customer.email}",
        )
    )
    db.add(
        Comment(
            ticket_id=ticket.id,
            author_id=agent.id,
            body=f"{FIXTURE_TAG} agent triage note for {customer.email}",
        )
    )
    return ticket


def _comment_ids(db, ticket_id: int) -> list[int]:
    return [
        c.id
        for c in db.scalars(
            select(Comment)
            .where(Comment.ticket_id == ticket_id)
            .order_by(Comment.id.asc())
        ).all()
    ]


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))


def _write_yaml_value(lines: list[str], value: Any, indent: int) -> None:
    prefix = " " * indent
    if isinstance(value, dict):
        if not value:
            lines.append(f"{prefix}{{}}")
            return
        for key, item in value.items():
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}{key}:")
                _write_yaml_value(lines, item, indent + 2)
            else:
                lines.append(f"{prefix}{key}: {_yaml_scalar(item)}")
    elif isinstance(value, list):
        if not value:
            lines.append(f"{prefix}[]")
            return
        for item in value:
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}-")
                _write_yaml_value(lines, item, indent + 2)
            else:
                lines.append(f"{prefix}- {_yaml_scalar(item)}")
    else:
        lines.append(f"{prefix}{_yaml_scalar(value)}")


def _emit(fixtures: list[dict[str, Any]]) -> None:
    lines = [
        "# Generated by niro/gen-fixtures.py. Do not edit by hand; rerun the",
        "# script to regenerate after resetting or reseeding the local target.",
        "fixtures:",
    ]
    for fixture in fixtures:
        lines.append(f"  - name: {fixture['name']}")
        lines.append(f"    description: {json.dumps(fixture['description'])}")
        lines.append("    value:")
        _write_yaml_value(lines, fixture["value"], 6)
        lines.append("")
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    Base.metadata.create_all(bind=engine)
    seed_users()

    db = SessionLocal()
    try:
        _clear_prior_fixtures(db)

        agent = _user(db, "agent@helpdesk.test")
        alex = _user(db, "alex@customer.test")
        blair = _user(db, "blair@customer.test")

        alex_ticket = _ticket(
            db,
            customer=alex,
            agent=agent,
            subject="customer A login reset",
            description="Customer A cannot complete the password reset flow.",
            priority=Priority.urgent,
            status=Status.open,
        )
        blair_ticket = _ticket(
            db,
            customer=blair,
            agent=agent,
            subject="customer B billing export",
            description="Customer B needs the invoice export regenerated.",
            priority=Priority.high,
            status=Status.in_progress,
        )
        db.commit()
        db.refresh(alex_ticket)
        db.refresh(blair_ticket)

        alex_comment_ids = _comment_ids(db, alex_ticket.id)
        blair_comment_ids = _comment_ids(db, blair_ticket.id)

        fixtures = [
            {
                "name": "seeded_actor_ids",
                "description": (
                    "README seeded users present in this boot. Use for role "
                    "and identity-aware authorization checks (also the CN on "
                    "each user's mTLS client cert for port 8443)."
                ),
                "value": {
                    "agent": {"id": agent.id, "email": agent.email, "role": agent.role.value},
                    "customer_a": {"id": alex.id, "email": alex.email, "role": alex.role.value},
                    "customer_b": {"id": blair.id, "email": blair.email, "role": blair.role.value},
                },
            },
            {
                "name": "cross_customer_ticket_pair",
                "description": (
                    "Different customer-owned tickets, each with a customer "
                    "comment and an agent comment. Customer A owns only "
                    "customer_a_ticket_id; customer B owns only "
                    "customer_b_ticket_id; the agent may access both. Use the "
                    "opposite customer's ticket/comment id as the cross-owner "
                    "target for IDOR / horizontal-escalation attempts on "
                    "/tickets/{id}, /tickets/{id}/comments, and the mTLS "
                    "/mtls/tickets/{id} surface."
                ),
                "value": {
                    "customer_a_ticket_id": alex_ticket.id,
                    "customer_a_comment_ids": alex_comment_ids,
                    "customer_b_ticket_id": blair_ticket.id,
                    "customer_b_comment_ids": blair_comment_ids,
                    "agent_assignee_id": agent.id,
                },
            },
        ]
        _emit(fixtures)
        print(f"-> wrote {OUT}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
